### ISSUE TITLE
Values with double quotes raises error

### ISSUE THREAD

**Issue by noobiwan** [Semantic-Org/UI-Dropdown#8]
There is an issue with values with double quotes. If you allow addition and you type a value with double quotes, it throws an error on this line:

https://github.com/Semantic-Org/UI-Dropdown/blob/master/dropdown.js#L2353

```js
optionValue: function(value) {
            var
              $option   = $input.find('option[value="' + value + '"]'),
              hasOption = ($option.length > 0)
            ;
```

As you can see, the value should be properly escaped. Maybe something like this:

```js
optionValue: function(value) {
            var escapedValue = value.replace(/"/g, '&quot;');
            var
              $option   = $input.find('option[value="' + escapedValue + '"]'),
              hasOption = ($option.length > 0)
            ;
```

Please advise.

**Comment by jlukic** [comment]
Please contribute to main repo and be sure to read contributing guide.
